language: node_js
node_js:
  - '10.15.3'
install:
  - yarn
script:
  - yarn build
  - cp -r ./dist/* .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${gh_token}
  on:
    branch: master